"""initial domain schema

Revision ID: 497bec61c6e8
Revises:
Create Date: 2026-09-20 04:19:51.739136

Schema notes (see docs/architecture.md for the full rationale):

- IDs are UUIDs generated by Postgres (``gen_random_uuid()``, built into
  core since Postgres 13 — no extension required).
- Money is stored as integer minor units + a currency code, never a
  float, per the "exact monetary representation" invariant.
- ``price_observation`` is unique on (offer_id, collection_run_id): a
  run can add at most one observation per offer it touches, which is
  what makes re-running a collection idempotent without discarding a
  legitimate new observation on a later run.
- ``offer_match`` keeps history instead of overwriting: a partial
  unique index enforces at most one *active* match per offer, while
  superseded matches stay queryable for audit/explainability.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "497bec61c6e8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_ENUM_TYPES = [
    "CREATE TYPE source_kind AS ENUM ('lab_simulated', 'real')",
    "CREATE TYPE source_status AS ENUM ('candidate', 'enabled', 'disabled')",
    "CREATE TYPE page_type AS ENUM ('category', 'product')",
    "CREATE TYPE discovered_page_status AS ENUM ('pending', 'collected', 'failed')",
    "CREATE TYPE run_trigger AS ENUM ('manual', 'scheduled')",
    "CREATE TYPE run_status AS ENUM ('pending', 'running', 'succeeded', 'failed', 'partial')",
    "CREATE TYPE evidence_type AS ENUM ('discovery_page', 'listing_page')",
    "CREATE TYPE offer_condition AS ENUM ('new', 'used', 'refurbished', 'unknown')",
    "CREATE TYPE availability_status AS ENUM ('in_stock', 'out_of_stock', 'unknown')",
    "CREATE TYPE match_method AS ENUM ('rule:gtin_exact', 'rule:attributes', 'manual')",
]

_TABLES = [
    """
    CREATE TABLE source (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name TEXT NOT NULL,
        base_url TEXT NOT NULL UNIQUE,
        kind source_kind NOT NULL,
        status source_status NOT NULL DEFAULT 'candidate',
        adapter_name TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE discovered_page (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        source_id UUID NOT NULL REFERENCES source (id) ON DELETE CASCADE,
        url TEXT NOT NULL,
        canonical_url TEXT NOT NULL,
        page_type page_type NOT NULL,
        status discovered_page_status NOT NULL DEFAULT 'pending',
        first_discovered_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (source_id, canonical_url)
    )
    """,
    "CREATE INDEX discovered_page_source_status_idx ON discovered_page (source_id, status)",
    """
    CREATE TABLE collection_run (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        source_id UUID NOT NULL REFERENCES source (id) ON DELETE CASCADE,
        trigger run_trigger NOT NULL,
        status run_status NOT NULL DEFAULT 'pending',
        idempotency_key TEXT NOT NULL UNIQUE,
        started_at TIMESTAMPTZ,
        finished_at TIMESTAMPTZ,
        stats JSONB NOT NULL DEFAULT '{}'::jsonb,
        failure_reason TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX collection_run_source_created_idx ON collection_run (source_id, created_at DESC)",
    """
    CREATE TABLE seller (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        source_id UUID NOT NULL REFERENCES source (id) ON DELETE CASCADE,
        external_id TEXT NOT NULL,
        display_name TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (source_id, external_id)
    )
    """,
    """
    CREATE TABLE product (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name TEXT NOT NULL,
        brand TEXT NOT NULL,
        category TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    """
    CREATE TABLE variant (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        product_id UUID NOT NULL REFERENCES product (id) ON DELETE CASCADE,
        attributes JSONB NOT NULL,
        attributes_signature TEXT NOT NULL,
        gtin TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (product_id, attributes_signature)
    )
    """,
    "CREATE UNIQUE INDEX variant_gtin_key ON variant (gtin) WHERE gtin IS NOT NULL",
    """
    CREATE TABLE offer (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        source_id UUID NOT NULL REFERENCES source (id) ON DELETE CASCADE,
        seller_id UUID NOT NULL REFERENCES seller (id) ON DELETE CASCADE,
        external_listing_id TEXT NOT NULL,
        url TEXT NOT NULL,
        raw_title TEXT NOT NULL,
        first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        last_price_minor_units BIGINT,
        last_price_currency CHAR(3),
        last_verified_at TIMESTAMPTZ,
        last_changed_at TIMESTAMPTZ,
        UNIQUE (source_id, external_listing_id)
    )
    """,
    """
    CREATE TABLE offer_match (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        offer_id UUID NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
        variant_id UUID NOT NULL REFERENCES variant (id) ON DELETE CASCADE,
        confidence NUMERIC(4, 3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
        method match_method NOT NULL,
        rationale TEXT NOT NULL,
        matched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        is_active BOOLEAN NOT NULL DEFAULT true
    )
    """,
    "CREATE UNIQUE INDEX offer_match_active_unique ON offer_match (offer_id) WHERE is_active",
    "CREATE INDEX offer_match_variant_idx ON offer_match (variant_id) WHERE is_active",
    """
    CREATE TABLE price_observation (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        offer_id UUID NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
        collection_run_id UUID NOT NULL REFERENCES collection_run (id) ON DELETE CASCADE,
        observed_at TIMESTAMPTZ NOT NULL,
        price_minor_units BIGINT NOT NULL CHECK (price_minor_units >= 0),
        currency CHAR(3) NOT NULL,
        availability availability_status NOT NULL,
        condition offer_condition NOT NULL,
        payment_terms JSONB NOT NULL DEFAULT '{}'::jsonb,
        shipping JSONB NOT NULL DEFAULT '{"known": false}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (offer_id, collection_run_id)
    )
    """,
    "CREATE INDEX price_observation_offer_observed_idx ON price_observation (offer_id, observed_at DESC)",
    """
    CREATE TABLE evidence (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        collection_run_id UUID NOT NULL REFERENCES collection_run (id) ON DELETE CASCADE,
        source_id UUID NOT NULL REFERENCES source (id) ON DELETE CASCADE,
        offer_id UUID REFERENCES offer (id) ON DELETE SET NULL,
        evidence_type evidence_type NOT NULL,
        url TEXT NOT NULL,
        http_status INTEGER,
        extractor_name TEXT NOT NULL,
        extractor_version TEXT NOT NULL,
        content_hash TEXT NOT NULL,
        raw_excerpt TEXT NOT NULL,
        fetched_at TIMESTAMPTZ NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
    )
    """,
    "CREATE INDEX evidence_source_url_idx ON evidence (source_id, url, fetched_at DESC)",
]

_TABLE_NAMES_IN_DROP_ORDER = [
    "evidence",
    "price_observation",
    "offer_match",
    "offer",
    "variant",
    "product",
    "seller",
    "collection_run",
    "discovered_page",
    "source",
]

_ENUM_NAMES = [
    "match_method",
    "availability_status",
    "offer_condition",
    "evidence_type",
    "run_status",
    "run_trigger",
    "discovered_page_status",
    "page_type",
    "source_status",
    "source_kind",
]


def upgrade() -> None:
    for statement in _ENUM_TYPES + _TABLES:
        op.execute(statement)


def downgrade() -> None:
    for table in _TABLE_NAMES_IN_DROP_ORDER:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")
    for enum in _ENUM_NAMES:
        op.execute(f"DROP TYPE IF EXISTS {enum}")
